"""Common test protocol and Host execution public API."""

from .host import HostTestRunner
from .model import (
    CASE_STATES,
    EVENT_KINDS,
    MAX_FRAME_PAYLOAD_BYTES,
    MAX_RUN_STREAM_BYTES,
    RUN_STATES,
    TEST_SCHEMA,
    TestCaseResult,
    TestInventory,
    TestProtocolError,
    TestRunManifest,
    calculate_host_build_inventory_digest,
    calculate_host_test_executable_inventory_digest,
    calculate_inventory_digest,
    create_inventory,
    host_target_device,
    validate_host_identity,
)
from .publication import PublishedTestRun, TestRunPublisher, TestRunRepository
from .protocol import (
    TARGET_FRAME_V1,
    TARGET_FRAME_V2,
    assemble_target_v2_run,
    assemble_test_run,
    calculate_case_inventory_digest,
    validate_event_payload,
)
from .replay import (
    TargetReplayDescriptor,
    TargetReplayError,
    TargetReplayFixture,
    TARGET_REPLAY_TRANSPORT,
    calculate_replay_id,
    canonical_replay_json_bytes,
    load_target_replay_fixture,
)

__all__ = [
    "CASE_STATES",
    "EVENT_KINDS",
    "HostTestRunner",
    "MAX_FRAME_PAYLOAD_BYTES",
    "MAX_RUN_STREAM_BYTES",
    "RUN_STATES",
    "TEST_SCHEMA",
    "TestCaseResult",
    "TestInventory",
    "TestProtocolError",
    "TestRunManifest",
    "TargetReplayDescriptor",
    "TargetReplayError",
    "TargetReplayFixture",
    "TARGET_FRAME_V1",
    "TARGET_FRAME_V2",
    "TARGET_REPLAY_TRANSPORT",
    "PublishedTestRun",
    "TestRunPublisher",
    "TestRunRepository",
    "assemble_target_v2_run",
    "assemble_test_run",
    "calculate_case_inventory_digest",
    "calculate_host_build_inventory_digest",
    "calculate_host_test_executable_inventory_digest",
    "calculate_inventory_digest",
    "calculate_replay_id",
    "canonical_replay_json_bytes",
    "create_inventory",
    "host_target_device",
    "validate_event_payload",
    "validate_host_identity",
    "load_target_replay_fixture",
]
