"""Project-isolated monitoring service for STM32 Toolkit."""

from .analysis import (
    ANALYSIS_COMPUTATION_SCHEMA,
    ANALYSIS_EVIDENCE_REF_SCHEMA,
    ANALYSIS_LINEAGE_SCHEMA,
    ANALYSIS_REQUEST_INVALID,
    ANALYSIS_REQUEST_SCHEMA,
    ANALYSIS_RESULT_SCHEMA,
    DIAGNOSTIC_MARKER_SCHEMA,
    AnalysisComputation,
    AnalysisEvidenceRef,
    AnalysisError,
    AnalysisLineage,
    AnalysisRequest,
    AnalysisResult,
    DiagnosticMarker,
    analyze_monitor_windows,
)
from .analysis_workflows import (
    ANALYSIS_WORKFLOW_INVALID,
    ENVIRONMENT_FAILURE,
    EVIDENCE_INTEGRITY_FAILURE,
    INCOMPATIBLE_IDENTITY,
    OPERATION_CONFLICT,
    AnalysisPublication,
    AnalysisBundleRef,
    AnalysisWorkflowError,
    compare_monitor_runs,
    export_analysis_bundle,
)
from .models import MonitorConfig, ProbeConnectRequest, WatchGroup, WatchItem
from .protocol import MONITOR_PROTOCOL_VERSION, ProtocolResult
from .replay import (
    EVIDENCE_INTEGRITY_FAILURE,
    ENVIRONMENT_FAILURE,
    MONITOR_REPLAY_INVALID,
    OPERATION_CONFLICT,
    MonitorReplayDocument,
    MonitorReplayError,
    MonitorRunRef,
    canonical_replay_json_bytes,
    ingest_monitor_replay,
)


__version__ = "0.5.0"

__all__ = [
    "MONITOR_PROTOCOL_VERSION",
    "ANALYSIS_COMPUTATION_SCHEMA",
    "ANALYSIS_EVIDENCE_REF_SCHEMA",
    "ANALYSIS_LINEAGE_SCHEMA",
    "ANALYSIS_REQUEST_INVALID",
    "ANALYSIS_REQUEST_SCHEMA",
    "ANALYSIS_RESULT_SCHEMA",
    "DIAGNOSTIC_MARKER_SCHEMA",
    "AnalysisComputation",
    "AnalysisEvidenceRef",
    "AnalysisError",
    "AnalysisLineage",
    "AnalysisRequest",
    "AnalysisResult",
    "DiagnosticMarker",
    "analyze_monitor_windows",
    "ANALYSIS_WORKFLOW_INVALID",
    "ENVIRONMENT_FAILURE",
    "EVIDENCE_INTEGRITY_FAILURE",
    "INCOMPATIBLE_IDENTITY",
    "OPERATION_CONFLICT",
    "AnalysisPublication",
    "AnalysisBundleRef",
    "AnalysisWorkflowError",
    "compare_monitor_runs",
    "export_analysis_bundle",
    "MonitorConfig",
    "ProbeConnectRequest",
    "ProtocolResult",
    "WatchGroup",
    "WatchItem",
    "EVIDENCE_INTEGRITY_FAILURE",
    "ENVIRONMENT_FAILURE",
    "MONITOR_REPLAY_INVALID",
    "OPERATION_CONFLICT",
    "MonitorReplayDocument",
    "MonitorReplayError",
    "MonitorRunRef",
    "canonical_replay_json_bytes",
    "ingest_monitor_replay",
    "__version__",
]
