import type {MonitorStatus,ObservationBinding,ParsedLiveEnvelope,WatchGroup} from "../api/contract";
import {appendAuthoritativeSample,appendContinuityGap,emptyLive,addSampleDropDeltas,watchKey,projectHistoryPage} from "../chart/series";
import {initialZoom,zoomReducer} from "../chart/zoom";
import {draftFromGroup,emptyDraft,type DropTotals,type LiveState,type MonitorAction,type MonitorState} from "./model";

const zeroDrops=():DropTotals=>({subscriber:0n,history:0n,deadline:0n,service:0n});
const dropsFrom=(status:MonitorStatus):DropTotals=>({subscriber:status.sampling.subscriberDrops,history:status.sampling.historyDrops,deadline:status.sampling.deadlineDrops,service:status.sampling.serviceDrops});
const liveForStatus=(status:MonitorStatus,selected:ReadonlySet<string>):LiveState=>({...emptyLive(),selectedSeries:new Set([...selected].slice(0,8)),bindingEpoch:status.sampling.bindingEpoch,runId:status.sampling.runId,authoritativeDrops:dropsFrom(status)});
const emptyProjection={rows:[],series:new Map()};
export const initialState:MonitorState={status:null,probes:[],groups:[],selectedGroupId:null,groupDraft:emptyDraft,stateRevision:-1n,lastAcceptedEventId:null,pending:{},failures:{},catalog:{variables:null,registers:null},selectedSeries:new Set(),live:emptyLive(),zoom:initialZoom,transport:{open:false,stale:false,needsStatusRefresh:false},history:{query:null,page:null,projection:emptyProjection,cursorIndex:0,nextCursor:null},exports:{artifact:null},notices:[],blockingError:null};
const sameBinding=(a:ObservationBinding,b:ObservationBinding):boolean=>a.workspaceId===b.workspaceId&&a.sessionId===b.sessionId&&a.logicalProjectId===b.logicalProjectId&&a.probeId===b.probeId&&a.targetDevice===b.targetDevice&&a.physicalTarget===b.physicalTarget&&a.buildId===b.buildId&&a.elfSha256===b.elfSha256&&a.inputSnapshotSha256===b.inputSnapshotSha256&&a.gitHead===b.gitHead&&a.gitDirty===b.gitDirty&&a.flashSessionId===b.flashSessionId&&a.leaseId===b.leaseId&&a.dwarfSha256===b.dwarfSha256&&a.svdSha256===b.svdSha256;
const statusMatches=(status:MonitorStatus,binding:ObservationBinding):boolean=>status.workspaceId===binding.workspaceId&&status.sessionId===binding.sessionId&&status.project.logicalProjectId===binding.logicalProjectId&&status.project.targetDevice===binding.targetDevice&&status.probe.connected&&status.probe.probeId===binding.probeId&&status.firmware!==null&&status.firmware.buildId===binding.buildId&&status.firmware.elfSha256===binding.elfSha256&&status.firmware.inputSnapshotSha256===binding.inputSnapshotSha256&&status.firmware.gitHead===binding.gitHead&&status.firmware.gitDirty===binding.gitDirty&&status.firmware.targetDevice===binding.targetDevice;
const catalogBindingKey=(status:MonitorStatus):string=>`${status.workspaceId}/${status.sessionId}/${status.project.logicalProjectId}/${status.sampling.bindingEpoch}`;
const rebased=(live:LiveState,status:MonitorStatus):LiveState=>({...live,authoritativeDrops:dropsFrom(status),pendingDropDeltas:zeroDrops(),bindingEpoch:status.sampling.bindingEpoch,runId:status.sampling.runId});
const sameFirmware=(left:MonitorStatus["firmware"],right:MonitorStatus["firmware"]):boolean=>left===null?right===null:right!==null&&left.buildId===right.buildId&&left.elfSha256===right.elfSha256&&left.inputSnapshotSha256===right.inputSnapshotSha256&&left.gitHead===right.gitHead&&left.gitDirty===right.gitDirty&&left.targetDevice===right.targetDevice;
const resetForStatus=(state:MonitorState,status:MonitorStatus):boolean=>{const prior=state.status;return prior!==null&&(prior.workspaceId!==status.workspaceId||prior.sessionId!==status.sessionId||prior.project.logicalProjectId!==status.project.logicalProjectId||prior.project.targetDevice!==status.project.targetDevice||!sameFirmware(prior.firmware,status.firmware)||prior.probe.connected!==status.probe.connected||prior.probe.probeId!==status.probe.probeId||prior.sampling.bindingEpoch!==status.sampling.bindingEpoch||prior.sampling.runId!==status.sampling.runId);};
const selectFirst=(groups:readonly WatchGroup[],selectedId:string|null):WatchGroup|null=>selectedId===null?groups[0]??null:groups.find(group=>group.groupId===selectedId)??groups[0]??null;
const resetNotice=(state:MonitorState,text:string)=>[...state.notices,{id:`view-reset-${state.notices.length}`,kind:"view-reset" as const,text}];

export function reduceAcceptedLiveEnvelope(state:MonitorState,envelope:ParsedLiveEnvelope):MonitorState{
 const {event,subscriberDropped}=envelope;if(state.lastAcceptedEventId!==null&&event.eventId<=state.lastAcceptedEventId)return state;let next:MonitorState={...state,lastAcceptedEventId:event.eventId,transport:{...state.transport,stale:false}};if(subscriberDropped>0n)next={...next,live:appendContinuityGap(next.live),zoom:initialZoom,transport:{...next.transport,needsStatusRefresh:true}};
 if(event.type==="hello")return {...next,stateRevision:event.data.stateRevision>state.stateRevision?event.data.stateRevision:state.stateRevision};
 if(event.type==="heartbeat")return next;
 if(event.type==="state"){
  if(event.data.stateRevision<state.stateRevision)return next;const changed=resetForStatus(state,event.data.status);let live=changed?liveForStatus(event.data.status,state.selectedSeries):rebased(next.live,event.data.status);const gap=event.data.gap||subscriberDropped>0n;if(event.data.gap&&subscriberDropped===0n)live=appendContinuityGap(live);
  return {...next,status:event.data.status,stateRevision:event.data.stateRevision,live,zoom:changed||gap?initialZoom:next.zoom,catalog:changed?{variables:null,registers:null}:state.catalog,transport:{...next.transport,needsStatusRefresh:gap||next.transport.needsStatusRefresh},notices:changed||gap?resetNotice(state,changed?"Live view reset for a new binding or run":"Live event gap; status refresh required"):state.notices};
 }
 const batch=event.data.batch,group=state.groups.find(item=>item.groupId===batch.groupId&&item.revision===batch.groupRevision);
 if(state.status===null||group===undefined||!statusMatches(state.status,batch.binding)||state.status.sampling.bindingEpoch!==state.live.bindingEpoch||state.status.sampling.runId!==batch.runId||(state.live.binding!==null&&!sameBinding(state.live.binding,batch.binding)))return {...next,transport:{...next.transport,stale:true}};
 let live=addSampleDropDeltas({...state.live,selectedSeries:new Set([...state.selectedSeries].slice(0,8))},batch,event.data.serviceSubscriberDrops);live=appendAuthoritativeSample(live,batch,group,state.selectedSeries);if(subscriberDropped>0n)live=appendContinuityGap(live);
 return {...next,live,zoom:subscriberDropped>0n?initialZoom:state.zoom,transport:{...next.transport,needsStatusRefresh:subscriberDropped>0n||state.transport.needsStatusRefresh}};
}

export function reducer(state:MonitorState,action:MonitorAction):MonitorState{
 if(action.type==="live.envelope")return reduceAcceptedLiveEnvelope(state,action.value);
 if(action.type==="initial.loaded"){const selected=action.groups[0]??null;return {...state,status:action.status,probes:action.probes,groups:action.groups,selectedGroupId:selected?.groupId??null,groupDraft:selected===null?emptyDraft:draftFromGroup(selected),live:liveForStatus(action.status,state.selectedSeries)};}
 if(action.type==="status.loaded"){const changed=resetForStatus(state,action.status);return {...state,status:action.status,live:changed?liveForStatus(action.status,state.selectedSeries):rebased(state.live,action.status),zoom:changed?initialZoom:state.zoom,catalog:changed?{variables:null,registers:null}:state.catalog,transport:{...state.transport,needsStatusRefresh:false},notices:changed?resetNotice(state,"Live view reset for a new binding or run"):state.notices};}
 if(action.type==="probes.loaded")return {...state,probes:action.probes};
 if(action.type==="groups.loaded"){const selected=selectFirst(action.groups,state.selectedGroupId);return {...state,groups:action.groups,selectedGroupId:selected?.groupId??null,groupDraft:selected===null?emptyDraft:draftFromGroup(selected)};}
 if(action.type==="catalog.requested"){if(state.status===null||catalogBindingKey(state.status)!==action.bindingKey)return state;if(action.catalog==="variables"){const prior=state.catalog.variables,append=action.cursor!==null&&prior!==null&&prior.query===action.query&&prior.bindingKey===action.bindingKey&&prior.nextCursor===action.cursor;return {...state,catalog:{...state.catalog,variables:{kind:"variables",query:action.query,bindingKey:action.bindingKey,cursor:action.cursor,items:append?prior.items:[],nextCursor:null}}};}const prior=state.catalog.registers,append=action.cursor!==null&&prior!==null&&prior.query===action.query&&prior.bindingKey===action.bindingKey&&prior.nextCursor===action.cursor;return {...state,catalog:{...state.catalog,registers:{kind:"registers",query:action.query,bindingKey:action.bindingKey,cursor:action.cursor,items:append?prior.items:[],nextCursor:null}}};}
 if(action.type==="catalog.loaded"){if(state.status===null||catalogBindingKey(state.status)!==action.bindingKey)return state;if(action.catalog==="variables"){const pending=state.catalog.variables;if(pending===null||pending.query!==action.query||pending.bindingKey!==action.bindingKey||pending.cursor!==action.cursor)return state;return {...state,catalog:{...state.catalog,variables:{...pending,items:action.cursor===null?action.items:[...pending.items,...action.items],nextCursor:action.nextCursor}}};}const pending=state.catalog.registers;if(pending===null||pending.query!==action.query||pending.bindingKey!==action.bindingKey||pending.cursor!==action.cursor)return state;return {...state,catalog:{...state.catalog,registers:{...pending,items:action.cursor===null?action.items:[...pending.items,...action.items],nextCursor:action.nextCursor}}};}
 if(action.type==="group.selected"){const selected=action.groupId===null?null:state.groups.find(group=>group.groupId===action.groupId)??null;return {...state,selectedGroupId:selected?.groupId??null,groupDraft:selected===null?emptyDraft:draftFromGroup(selected)};}
 if(action.type==="group.draft.changed")return {...state,groupDraft:action.draft};
 if(action.type==="group.watch.added")return state.groupDraft.items.some(item=>watchKey(item)===watchKey(action.watch))?state:{...state,groupDraft:{...state.groupDraft,items:[...state.groupDraft.items,action.watch]}};
 if(action.type==="group.watch.removed"){const items=state.groupDraft.items.filter(item=>watchKey(item)!==action.key);return items.length===state.groupDraft.items.length?state:{...state,groupDraft:{...state.groupDraft,items}};}
 if(action.type==="series.toggled"){const selected=new Set(state.selectedSeries);if(selected.has(action.key))selected.delete(action.key);else if(selected.size<8)selected.add(action.key);else return state;return {...state,selectedSeries:selected,live:{...state.live,selectedSeries:selected}};}
 if(action.type==="zoom.changed")return {...state,zoom:zoomReducer(state.zoom,action.action)};
 if(action.type==="zoom.reset")return {...state,zoom:initialZoom};
 if(action.type==="history.loaded"){const projection=projectHistoryPage(action.page,new Map(state.groups.map(group=>[group.groupId,group])),state.selectedSeries);return {...state,history:{query:action.query,page:action.page,projection,cursorIndex:0,nextCursor:action.page.nextCursor}};}
 if(action.type==="export.loaded")return {...state,exports:{artifact:action.artifact}};
 if(action.type==="request.started")return {...state,pending:{...state.pending,[action.scope]:{requestId:action.requestId}},failures:{...state.failures,[action.scope]:undefined}};
 if(action.type==="request.cleared"){const pending=state.pending[action.scope];if(pending===undefined||pending.requestId!==action.requestId)return state;const copy={...state.pending};delete copy[action.scope];return {...state,pending:copy};}
 if(action.type==="request.failed"){const pending=state.pending[action.scope];if(pending===undefined||pending.requestId!==action.requestId)return state;const copy={...state.pending};delete copy[action.scope];return {...state,pending:copy,failures:{...state.failures,[action.scope]:{ok:false,code:action.code,message:action.message}},blockingError:{ok:false,code:action.code,message:action.message}};}
 return action.type==="transport.open"?{...state,transport:{...state.transport,open:true,stale:false}}:{...state,transport:{...state.transport,open:false,stale:true}};
}
